/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JUAN S. GOMEZ URIBE
 */
public class GUI_MenuPadre extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuPadre
     */
    public GUI_MenuPadre() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhijo = new javax.swing.JButton();
        btnpadre = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhijo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnhijo.setForeground(new java.awt.Color(255, 0, 0));
        btnhijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chico.png"))); // NOI18N
        btnhijo.setText("Informacion de Hijos");
        btnhijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhijoActionPerformed(evt);
            }
        });
        getContentPane().add(btnhijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 260, 80));

        btnpadre.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnpadre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/padre.png"))); // NOI18N
        btnpadre.setText("Informacion de Padre");
        btnpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpadreActionPerformed(evt);
            }
        });
        getContentPane().add(btnpadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 260, 80));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-wallpaper-24.jpg"))); // NOI18N
        lblfondo.setText("jLabel1");
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhijoActionPerformed
        // TODO add your handling code here:
        GUI_Hijo h=new GUI_Hijo();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnhijoActionPerformed

    private void btnpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpadreActionPerformed
        // TODO add your handling code here:
        GUI_Padre p=new GUI_Padre();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnpadreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuPadre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuPadre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhijo;
    private javax.swing.JButton btnpadre;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
