/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JUAN S. GOMEZ URIBE
 */
public class GUI_MenuDoctor extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MenuDoctor
     */
    public GUI_MenuDoctor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btninformacion = new javax.swing.JButton();
        btnvacunas = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btninformacion.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btninformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/doctor.png"))); // NOI18N
        btninformacion.setText("Informacion de Doctor");
        btninformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformacionActionPerformed(evt);
            }
        });
        getContentPane().add(btninformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        btnvacunas.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnvacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/jeringa.png"))); // NOI18N
        btnvacunas.setText("Informacion de Vacunas");
        btnvacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvacunasActionPerformed(evt);
            }
        });
        getContentPane().add(btnvacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 260, -1));

        btnconsultar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seo.png"))); // NOI18N
        btnconsultar.setText("Consultar Registros de Vacunas");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnconsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 300, 70));

        btnagregar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add-file.png"))); // NOI18N
        btnagregar.setText("Agregar Registro de Vacuna");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-wallpaper-24.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 355));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformacionActionPerformed
        // TODO add your handling code here:
        GUI_Doctor d=new GUI_Doctor();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btninformacionActionPerformed

    private void btnvacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvacunasActionPerformed
        // TODO add your handling code here:
        GUI_Vacuna v=new GUI_Vacuna();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnvacunasActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        GUI_RegistroVacunas rv=new GUI_RegistroVacunas();
        rv.setVisible(true);
        rv.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
        GUI_AgregarRegistro ar=new GUI_AgregarRegistro();
        ar.setVisible(true);
        ar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MenuDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btninformacion;
    private javax.swing.JButton btnvacunas;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
