/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author Estudiante
 */
public class GUI_Administrador extends javax.swing.JFrame {

    private static final ImageIcon icono = new ImageIcon(GUI_Administrador.class.getResource("/imagenes/jeringa.png"));
    public GUI_Administrador() {
        initComponents();
        this.setIconImage(icono.getImage());
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnHijos = new javax.swing.JButton();
        btnPadres = new javax.swing.JButton();
        btnDoctores = new javax.swing.JButton();
        btnVacunas = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Donde desea entrar?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 24, -1, -1));

        btnHijos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnHijos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4043250-avatar-child-girl-kid_113270.png"))); // NOI18N
        btnHijos.setText("Hijos");
        btnHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijosActionPerformed(evt);
            }
        });
        getContentPane().add(btnHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnPadres.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnPadres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dad-avatar_114341.png"))); // NOI18N
        btnPadres.setText("Padres");
        btnPadres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadresActionPerformed(evt);
            }
        });
        getContentPane().add(btnPadres, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        btnDoctores.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnDoctores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Doctor_Male_icon-icons.com_75051.png"))); // NOI18N
        btnDoctores.setText("Doctores");
        btnDoctores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnDoctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnVacunas.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnVacunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/18_113669.png"))); // NOI18N
        btnVacunas.setText("Vacunas");
        btnVacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacunasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/blue-wallpaper-24.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijosActionPerformed
        GUI_AdminHijo h=new GUI_AdminHijo();
        h.setVisible(true);
        h.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnHijosActionPerformed

    private void btnPadresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadresActionPerformed
        // TODO add your handling code here:
        GUI_AdminPadre p=new GUI_AdminPadre();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPadresActionPerformed

    private void btnDoctoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctoresActionPerformed
        // TODO add your handling code here:
        GUI_AdminDoctor d=new GUI_AdminDoctor();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnDoctoresActionPerformed

    private void btnVacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacunasActionPerformed
        // TODO add your handling code here:
        GUI_AdminVacuna v=new GUI_AdminVacuna();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVacunasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctores;
    private javax.swing.JButton btnHijos;
    private javax.swing.JButton btnPadres;
    private javax.swing.JButton btnVacunas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblfondo;
    // End of variables declaration//GEN-END:variables
}
