/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author PC5
 */
public class GUI_Principal extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Principal
     */
    public GUI_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_padre = new javax.swing.JMenu();
        menu_hijos = new javax.swing.JMenu();
        insertar_hijo = new javax.swing.JMenuItem();
        modificar_hijo = new javax.swing.JMenuItem();
        consultar_hijo = new javax.swing.JMenuItem();
        eliminar_hijo = new javax.swing.JMenuItem();
        menu_vacunas = new javax.swing.JMenu();
        insertar_vacuna = new javax.swing.JMenuItem();
        modificar_vacuna = new javax.swing.JMenuItem();
        consultar_vacuna = new javax.swing.JMenuItem();
        eliminar_vacuna = new javax.swing.JMenuItem();
        menu_doctor = new javax.swing.JMenu();
        insertar_doctor = new javax.swing.JMenuItem();
        modificar_doctor = new javax.swing.JMenuItem();
        consultar_doctor = new javax.swing.JMenuItem();
        eliminar_doctor = new javax.swing.JMenuItem();
        menu_registro = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        menu_padre.setText("Padre");
        menu_padre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_padreMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_padre);

        menu_hijos.setText("Hijos");

        insertar_hijo.setText("Insertar Hijo");
        menu_hijos.add(insertar_hijo);

        modificar_hijo.setText("Modificar Hijo");
        modificar_hijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_hijoActionPerformed(evt);
            }
        });
        menu_hijos.add(modificar_hijo);

        consultar_hijo.setText("Consultar Hijo");
        consultar_hijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_hijoActionPerformed(evt);
            }
        });
        menu_hijos.add(consultar_hijo);

        eliminar_hijo.setText("Eliminar Hijo");
        menu_hijos.add(eliminar_hijo);

        jMenuBar1.add(menu_hijos);

        menu_vacunas.setText("Vacunas");

        insertar_vacuna.setText("Insertar Vacuna");
        menu_vacunas.add(insertar_vacuna);

        modificar_vacuna.setText("Modificar Vacuna");
        modificar_vacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_vacunaActionPerformed(evt);
            }
        });
        menu_vacunas.add(modificar_vacuna);

        consultar_vacuna.setText("Consultar Vacuna");
        menu_vacunas.add(consultar_vacuna);

        eliminar_vacuna.setText("Eliminar Vacuna");
        menu_vacunas.add(eliminar_vacuna);

        jMenuBar1.add(menu_vacunas);

        menu_doctor.setText("Doctor");

        insertar_doctor.setText("Insertar Doctor");
        menu_doctor.add(insertar_doctor);

        modificar_doctor.setText("Modificar Doctor");
        modificar_doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificar_doctorActionPerformed(evt);
            }
        });
        menu_doctor.add(modificar_doctor);

        consultar_doctor.setText("Consultar Doctor");
        menu_doctor.add(consultar_doctor);

        eliminar_doctor.setText("Eliminar Doctor");
        menu_doctor.add(eliminar_doctor);

        jMenuBar1.add(menu_doctor);

        menu_registro.setText("Registro Vacunas");
        jMenuBar1.add(menu_registro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificar_hijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_hijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_hijoActionPerformed

    private void consultar_hijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_hijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultar_hijoActionPerformed

    private void modificar_vacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_vacunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_vacunaActionPerformed

    private void modificar_doctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificar_doctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_doctorActionPerformed

    private void menu_padreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_padreMouseClicked
        
        
        
    }//GEN-LAST:event_menu_padreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultar_doctor;
    private javax.swing.JMenuItem consultar_hijo;
    private javax.swing.JMenuItem consultar_vacuna;
    private javax.swing.JMenuItem eliminar_doctor;
    private javax.swing.JMenuItem eliminar_hijo;
    private javax.swing.JMenuItem eliminar_vacuna;
    private javax.swing.JMenuItem insertar_doctor;
    private javax.swing.JMenuItem insertar_hijo;
    private javax.swing.JMenuItem insertar_vacuna;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu_doctor;
    private javax.swing.JMenu menu_hijos;
    private javax.swing.JMenu menu_padre;
    private javax.swing.JMenu menu_registro;
    private javax.swing.JMenu menu_vacunas;
    private javax.swing.JMenuItem modificar_doctor;
    private javax.swing.JMenuItem modificar_hijo;
    private javax.swing.JMenuItem modificar_vacuna;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables
}
