/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JUAN S. GOMEZ URIBE
 */
public class InstruccionDoctor extends javax.swing.JFrame {

    /**
     * Creates new form InstruccionDoctor
     */
    public InstruccionDoctor() {
        initComponents();
        txtinstruccion.setLineWrap(true);
        txtinstruccion.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtinstruccion = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();
        lblfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("INSTRUCCION DE USO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 210, -1));

        txtinstruccion.setEditable(false);
        txtinstruccion.setColumns(20);
        txtinstruccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtinstruccion.setLineWrap(true);
        txtinstruccion.setRows(5);
        txtinstruccion.setText("-Informacion de Doctor: En este apartado usted podra visualizar toda su informacion y podra actualizar estos datos, si usted desea. Para modificar sus datos solo basta con hacer seleccion en la tabla. Seguido de eso sus datos seran seteados en cada campo de texto, y ahi usted despues de modificar sus datos, debe presionar en modificar y automaticamente se actualizaran sus datos exitosamente\n\n-Informacion de Vacunas: En este apartado podra visualizar las vacunas existentes. Tambien si al momento de usar este programa se genera una nueva vacuna, usted tendra la opcion de poder registar esta nueva vacuna por medio del boton \"Agregar\".\n\n-Consultar Registro de Vacunas: En este modulo usted podra ver todos los registros que se le han realizado a un niño.\nSolo basta con seleccionarlo en la tabla donde se encontraran cargados todos los hijos, despues de seleccionarlos en la parte inferior podra ver todos los registros realizados a este niño.\n\n-Agregar Registro de Vacunas: Esta opcion será para, luego de usted realizar esa vacuna al niño, debe seleccionar al niño que le fue aplicada la vacuna, que vacuna se le aplicó, la fecha en la que aplicó y la fecha para la proxima vacuna del niño.\n \n-Enviar Aviso: Usted hara uso de esta funcion, para avisar al padre de X niño la fecha de la proxima vacuna, ya que a veces por algunas circunstancias lo olvidan.");
        jScrollPane1.setViewportView(txtinstruccion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 630, 430));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        lblfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo Blanco.jpg"))); // NOI18N
        getContentPane().add(lblfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        GUI_MenuDoctor mp = new GUI_MenuDoctor();
        mp.setVisible(true);
        mp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstruccionDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstruccionDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstruccionDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstruccionDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstruccionDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblfondo;
    private javax.swing.JTextArea txtinstruccion;
    // End of variables declaration//GEN-END:variables
}
